id: A887ACAFD
title: The Thirty Aspirations
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:19:39.536887
  last_modified_at: 2022-03-01 02:19:39.536894
